test:
	for file in ./*.java ; do \
		echo "Begin " $$file " parsing" ; \
		echo "-----------------------------------------------------------" ; \
		/opt/jdk1.8.0/bin/javac $$file ; \
		echo "-----------------------------------------------------------" ; \
		echo "End " $$file " parsing" ; \
	done
